### ISSUE TITLE
Table layout and carriage return

### ISSUE THREAD

**Issue by ncarboni** [timvink/mkdocs-table-reader-plugin#2] opened 2020-05-28 15:17 UTC
I am testing with this plugin and it is already fantastic, but I was wondering if there is a way to take into account carriage return within a cell.
I would like a cell to display
```
→ P108i → E12 → P32 → E55 
→ P108i → E12 → P2 → E55
```
But if I tried to load a CSV with a carriage return I obtain this:

<img width="1089" alt="csv_return" src="https://user-images.githubusercontent.com/5669838/83158611-46071880-a105-11ea-87f5-d5a7cf8462f4.png">

fair enough, it is a CSV. Using an excel file (using `{{ read_excel('file'.xlsx) }}` instead I obtain this result:

<img width="1095" alt="excel_return" src="https://user-images.githubusercontent.com/5669838/83158819-91212b80-a105-11ea-80de-2d99bc861854.png">

While nicer the result coming from excel do present a new line instead of a carriage return within the same cell. I was wondering if it would be possible to have a real carriage return, something like this (obtained using `<br>`):

<img width="690" alt="br_xls" src="https://user-images.githubusercontent.com/5669838/83160090-09d4b780-a107-11ea-9920-f2b77298b409.png">

**Comment by timvink** [comment] 2020-05-28 17:13
Thanks for the feedback, glad to hear you like it! And a different use case than I imaged when I created it, nice!

## Some technical context

This plugin uses `df.to_markdown()` to create markdown from a table. That's included in `pandas>=1.03`, but actually uses `tabulate` under the hood.

> **kwargs These parameters will be passed to tabulate.
[docs for pandas.DataFrame.to_markdown](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_markdown.html)

Currently, this is what the call looks like in this plugin:

https://github.com/timvink/mkdocs-table-reader-plugin/blob/1d75fbfc8cdb07c21b196065965a1e8e7845baff/mkdocs_table_reader_plugin/plugin.py#L10

There are other parameters supported by `tabulate`, see [python-tabulate](https://github.com/astanin/python-tabulate). Specifically the section on [line-breaks](https://github.com/astanin/python-tabulate#multiline-cells) is very relevant: _"Note that some output formats (e.g. simple, or plain) do not represent row delimiters, so that the representation of multiline cells in such formats may be ambiguous to the reader"_ . The default is `tablefmt="simple"` so it might be useful to try a different format. 

MkDocs uses [python-markdown](https://python-markdown.github.io/) which implements this [reference syntax](https://daringfireball.net/projects/markdown/syntax). That one doesn't include tables, which is why python-markdown has a [tables extension](https://python-markdown.github.io/extensions/tables/). That extension in turn uses the [PHP Extra Markdown](https://michelf.ca/projects/php-markdown/extra/#table) syntax for tables, which is supported by `tabulate` via `tablefmt="pipe"`, which is included in the list of output formats that support multiline cells!

That was a fun bit of detective work :) With this knowledge, I think `"pipe"` should be the default `tablefmt` for this plugin. I created a new merge request with the change in #3 that we can test.
 
## Possible solutions

1. The new default `tablefmt="pipe"` output setting. Can you test (by installing #3) if this solves your issue before I release a new version? Let me know if you need help installing from a branch!
1. If you are on windows, make sure your line endings are in unix format (`\n` instead of `\r\n`). [context](https://stackoverflow.com/questions/426397/do-line-endings-differ-between-windows-and-linux)

**Comment by ncarboni** [comment] 2020-05-29 07:40
Thanks for the explanation, it is quite useful to understand the possibilities. I quickly tried yesterday using tablefmt="pipe", but I still did not get any multiline. I will do some other testing today (I will try other tablefmt options and see if something change) and come back with more info. In the meanwhile, thank you very much!

**Comment by ncarboni** [comment] 2020-05-29 15:57
A bit of recap after some tests. 
I added tablefmt="pipe" (`return df.to_markdown(showindex=False, tablefmt="pipe"`) to read_csv and read_excel, and re-installed the package. However, I do not see any differences in the creation of the table. I tried with other table format from python-tabulate, but they did not seems to work either. 
I tried to inserti a `\n` in order to signal a `<br>` in the cell of the CSV or excel file, but also there I did not obtained a real carriage return but only a new row.
I am maybe doing something wrong from my side? Did you by any chance make it work?

**Comment by timvink** [comment] 2020-05-31 11:16
Did some experiments (and found + fixed a different bug in #4). 

This csv:

![image](https://user-images.githubusercontent.com/5570380/83349060-1a1caa80-a332-11ea-8794-05c79e1a960b.png)

Renders as:

![image](https://user-images.githubusercontent.com/5570380/83349070-2b65b700-a332-11ea-848e-d2673891b01c.png)

However inserting `<br/`> directly works as intended, and might already be the solution for your specific use-case:

![image](https://user-images.githubusercontent.com/5570380/83349299-1b4ed700-a334-11ea-9b44-f0632eb93a50.png)

![image](https://user-images.githubusercontent.com/5570380/83349300-20ac2180-a334-11ea-8892-3b3942710bf1.png)

It seems that the `csv` standard does not support escape characters like `\n` ([source](https://stackoverflow.com/questions/566052/can-you-encode-cr-lf-in-into-csv-files)).  Alternatively, specifying the newline differently in the CSV creates a new row but the alignment is proper:

![image](https://user-images.githubusercontent.com/5570380/83349407-f7d85c00-a334-11ea-8e48-c825b77384b7.png)

![image](https://user-images.githubusercontent.com/5570380/83349413-fe66d380-a334-11ea-86fd-7bdd4e0e0d25.png)

----

I'm not sure what the proper behaviour should be, and where that should be addressed. Most likely it's in `python-markdown` tables extension. But the root cause is not in `mkdocs-table-reader-plugin`, so I suggest to close this issue. I might investigate further and open a new issue elsewhere.

**Comment by timvink** [comment] 2020-05-31 12:14
FYI, I opened https://github.com/Python-Markdown/markdown/issues/975

**Comment by ncarboni** [comment] 2020-05-31 16:28
Thanks for the testing! If will use <br> for now and let's see if something will change from python-markdown side. Feel free to close :-)

**Comment by timvink** [comment] 2020-06-01 08:36
Long story short, for multiline cells the solution is to use `<br/>`. (see also the `python-markdown` issue). If you need anything more complex, you can always fall back to raw HTML tables.

**Closed by timvink** 2020-06-01 08:36 UTC
Labels: enhancement
